
/**
 * Constants for common text and style.
 */
export class CommonConstants {
  /**
   * The full size of container.
   */
  static readonly FULL_SIZE: string = '100%';

  /**
   * Content width.
   */
  static readonly CONTENT_WIDTH: string = '87%';

  /**
   * Content height.
   */
  static readonly CONTENT_HEIGHT: string = '90%';

  /**
   * Common value.
   */
  static readonly COMMON_VALUE: number = 480;
}